#!/bin/bash
git clone https://github.com/killajoe/EndeavourOS-Network-Printer-Setup.git
cd EndeavourOS-Network-Printer-Setup

## start script ##
systemctl enable cups-browsed.service
# creating a public zone dropin and backup
cp /usr/lib/firewalld/zones/home.xml /etc/firewalld/zones/
cp /usr/lib/firewalld/zones/home.xml /etc/firewalld/zones/home.xml.old
patch /etc/firewalld/zones/home.xml < home.xml.patch
# enable home as default zone
patch /etc/firewalld/firewalld.conf < firewalld.conf.patch
# enable local hostname resolution
patch /etc/nsswitch.conf < nsswitch.conf.patch
## end script ##

# cleanup
cd .. 
rm -R EndeavourOS-Network-Printer-Setup
