#!/bin/bash
git clone https://github.com/killajoe/EndeavourOS-Network-Printer-Setup.git
cd EndeavourOS-Network-Printer-Setup

## start script ##
systemctl enable cups-browsed.service
# creating a zone dropin
cp /usr/lib/firewalld/zones/home.xml /etc/firewalld/zones/network-printer.xml
patch /etc/firewalld/zones/network-printer.xml < network-printer.xml.patch
# enable home as default zone
patch /etc/firewalld/firewalld.conf < firewalld-new.conf.patch
# enable local hostname resolution
patch /etc/nsswitch.conf < nsswitch.conf.patch
## end script ##

# cleanup
cd .. 
rm -R EndeavourOS-Network-Printer-Setup
